apiVersion: apps/v1
kind: Deployment
metadata:
  name: concert-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: concert-service
  template:
    metadata:
      labels:
        app: concert-service
        env: prod
        app.kubernetes.io/name: concert-service
    spec:
      containers:
      - name: concert-service
        image: estherw66/concert-service:latest
        ports:
          - containerPort: 5100
            name: http-web-api
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        env:
          - name: ASPNETCORE_URLS
            value: http://+:5100
        readinessProbe:
          httpGet:
            path: /health
            port: 5100
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5100
          initialDelaySeconds: 15
          periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: concert-service-lb
spec:
  selector:
    app.kubernetes.io/name: concert-service
  ports:
    - name: concert-service-port
      protocol: TCP
      port: 5100
      targetPort: 5100
  type: LoadBalancer