apiVersion: apps/v1
kind: Deployment
metadata:
  name: concert-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: concert-service
  template:
    metadata:
      labels:
        app: concert-service
        env: prod
        app.kubernetes.io/name: concert-service
    spec:
      containers:
      - name: concert-service
        image: estherw66/concert-service:latest
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: DB_HOST
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: DB_PASSWORD
          - name: DB_NAME_CONCERT
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: DB_NAME_CONCERT
          - name: ASPNETCORE_URLS
            value: http://+:5100
        ports:
          - containerPort: 5100
            name: http-web-api
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi

---

apiVersion: v1
kind: Service
metadata:
  name: concert-service
spec:
  selector:
    app.kubernetes.io/name: concert-service
  ports:
    - name: concert-service-port
      protocol: TCP
      port: 5100
      targetPort: 5100