networks:
  cm-backend-network:
    external: true
    driver: bridge

services:
  database:
    container_name: concert.data
    image: mysql:latest
    ports:
      - '3307:3306'
    restart: always
    networks: 
      - cm-backend-network
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASS}'
      MYSQL_PASSWORD: '${DB_PASS}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_DATABASE: '${DB_DATABASE}'
    volumes:
      - cm_concert_data:/var/lib/mysql_data/data
  
  concert.api:
    container_name: concert.api
    image: concert.api
    depends_on: 
      - 'database'
    restart: always
    networks: 
      - cm-backend-network
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '5100:5100'
      - '5101:5101'
    environment:
      - ConnectionStrings__DefaultConnection=Server=concert.data;Port=3306;Database='${DB_DATABASE}';Uid='${DB_USER}';Pwd='${DB_PASS}';
      - ASPNETCORE_URLS=http://+:5100
    
  rabbitmq:
    container_name: "rabbitmq"
    image: "rabbitmq:3-management"
    networks:
      - cm-backend-network
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

volumes: 
  cm_concert_data:
    