apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  DB_HOST: Y29uY2VydC1kYXRhLm15c3FsLmRhdGFiYXNlLmF6dXJlLmNvbQ==
  DB_USER: bXlzcWw=
  DB_PASSWORD: Q291bnRpbmdTaGVlcDE=
  DB_NAME: Y29uY2VydC1kYXRh